-- return {
--     -- lsp symbol navigation for lualine. This shows where
--     -- in the code structure you are - within functions, classes,
--     -- etc - in the statusline.
--     {
--       "SmiteshP/nvim-navic",
--       lazy = true,
--       init = function()
--         vim.g.navic_silence = true
--         LazyVim.lsp.on_attach(function(client, buffer)
--           if client.supports_method("textDocument/documentSymbol") then
--             require("nvim-navic").attach(client, buffer)
--           end
--         end)
--       end,
--       opts = function()
--         return {
--           separator = "",
--           highlight = true,
--           depth_limit = 5,
--           icons = LazyVim.config.icons.kinds,
--           lazy_update_context = true,
--         }
--       end,
--     },
  
    -- lualine integration
    -- {
    --   "nvim-lualine/lualine.nvim",
    --   optional = true,
    --   opts = function(_, opts)
    --     -- if not vim.g.trouble_lualine then
    --     --   table.insert(opts.sections.lualine_c, { "navic", color_correction = "dynamic" })
    --     -- end
    --   end,
    -- },
--   }
-- -- -- Navic 아이콘의 배경색 설정
-- -- vim.api.nvim_set_hl(0, "NavicIconsFile", { fg = "#ff79c6", bg = "#282a36" }) -- 파일 아이콘
-- -- vim.api.nvim_set_hl(0, "NavicIconsClass", { fg = "#8be9fd", bg = "#282a36" }) -- 클래스 아이콘
-- -- vim.api.nvim_set_hl(0, "NavicIconsFunction", { fg = "#50fa7b", bg = "#282a36" }) -- 함수 아이콘

-- -- -- Navic 텍스트와 구분자의 배경색 설정
-- -- vim.api.nvim_set_hl(0, "NavicText", { fg = "#f8f8f2", bg = "#282a36" }) -- 텍스트 색상
-- -- vim.api.nvim_set_hl(0, "NavicSeparator", { fg = "#f8f8f2", bg = "#282a36" }) -- 구분자 색상